env:
- CGO_ENABLED=0
- GO111MODULE=on

before:
  hooks:
  - go mod tidy

builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

