name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - linux/arm
          - linux/arm64
          - linux/amd64
          - darwin/amd64
          - darwin/arm64
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Set go architecture
      run: |
        platforms="${{ matrix.arch }}"
        for platform in "${platforms[@]}"; do
          platform_split=(${platform//\// })
          echo "GOOS=${platform_split[0]}" >> $GITHUB_ENV
          echo "GOARCH=${platform_split[1]}" >> $GITHUB_ENV
        done

    - name: Build
      run: |
        go build -v -o "g-userping-${GOOS}-${GOARCH}"
